theme: jekyll-theme-cayman
title: Wake Fintech
description: This site hosts the latest information behind what's happening on Wake Forest's campus around Blockchain and Financial Technology
github_username: brockly
logo: /Wake_Fintech_Logo.png
