#theme: jekyll-theme-cayman
remote_theme: broccolini/swiss
theme_color: yellow
title: Wake Fintech
description: This site hosts the latest information behind what's happening on Wake Forest's campus around Blockchain and Financial Technology
github_username: brockly
logo: /Wake_Fintech_Logo.png
